"""
SCOUT PIOTR
FILLETTE PERRINE
GAMIN BEN
CAMPEUR RACHID
INTELLO LUC
CROUPIER STANISLAS
MOTARD RICARDO
MONTAGNARD MAURICE
POKéMANIAC ACHILLE
MECANO BERNARD
PECHEUR ERWAN
JEUNE COUPLE GIA & JES
ROCKER ELTON
ORNITHOLOGUE SEBASTIEN
CANON LEA
JUMELLES JOY & KATE
DUO BASTON RON & MYA
LOUBARD JEOFFREY
NAGEUR RICHARD
FRERE & SOEUR VIVI & SAM
NAGEUSE SHIRLEY
RIVAL
PIERRE
"""

def interaction():
    # quand on clique pour parler au personnage
